language: node_js

node_js:
  - "11"
  - node

dist: trusty

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:
  - npm run mock:create

script:
  - npm run test
  - npm run lint

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage --coverageReporters=text-lcov | coveralls